CREATE TABLE audit_logs
(
    id           NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ticket_id    NUMBER(38, 0)                                  NOT NULL,
    action       VARCHAR2(255)                                  NOT NULL,
    timestamp    TIMESTAMP NOT NULL,
    performed_by NUMBER(38, 0)                                  NOT NULL,
    old_status   VARCHAR2(255),
    new_status   VARCHAR2(255),
    comment_id   NUMBER(38, 0),
    CONSTRAINT pk_audit_logs PRIMARY KEY (id)
);

CREATE TABLE comments
(
    id         NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content    VARCHAR2(1000)                                 NOT NULL,
    created_at TIMESTAMP NOT NULL,
    ticket_id  NUMBER(38, 0)                                  NOT NULL,
    created_by NUMBER(38, 0)                                  NOT NULL,
    CONSTRAINT pk_comments PRIMARY KEY (id)
);

CREATE TABLE tickets
(
    id            NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title         VARCHAR2(255)                                  NOT NULL,
    description   VARCHAR2(1000)                                 NOT NULL,
    priority      VARCHAR2(255)                                  NOT NULL,
    category      VARCHAR2(255)                                  NOT NULL,
    status        VARCHAR2(255)                                  NOT NULL,
    creation_date TIMESTAMP NOT NULL,
    created_by    NUMBER(38, 0)                                  NOT NULL,
    CONSTRAINT pk_tickets PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR2(255)                                  NOT NULL,
    email    VARCHAR2(255)                                  NOT NULL,
    password VARCHAR2(255)                                  NOT NULL,
    role     VARCHAR2(255)                                  NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE audit_logs
    ADD CONSTRAINT FK_AUDIT_LOGS_ON_COMMENT FOREIGN KEY (comment_id) REFERENCES comments (id);

ALTER TABLE audit_logs
    ADD CONSTRAINT FK_AUDIT_LOGS_ON_PERFORMED_BY FOREIGN KEY (performed_by) REFERENCES users (id);

ALTER TABLE audit_logs
    ADD CONSTRAINT FK_AUDIT_LOGS_ON_TICKET FOREIGN KEY (ticket_id) REFERENCES tickets (id);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES users (id);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_TICKET FOREIGN KEY (ticket_id) REFERENCES tickets (id);

ALTER TABLE tickets
    ADD CONSTRAINT FK_TICKETS_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES users (id);